CREATE TABLE IF NOT EXISTS trash_reminders_sent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  calendar_entry_id INTEGER NOT NULL UNIQUE REFERENCES calendar_entries(id) ON DELETE CASCADE,
  sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
